services:
  discord-bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: gamers-discord-bot
    env_file:
      - ../env/.env
    networks:
      - gamers-network
    restart: unless-stopped

networks:
  gamers-network:
    external: true